[0m23:36:41.070308 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1be2789250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1be1d14aa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1be19d6ff0>]}


============================== 23:36:41.100395 | 29bf08d6-231f-48a0-9a7e-65596b91b1c2 ==============================
[0m23:36:41.100395 [info ] [MainThread]: Running with dbt=1.10.11
[0m23:36:41.100876 [debug] [MainThread]: running dbt with arguments {'indirect_selection': 'eager', 'target_path': 'None', 'quiet': 'False', 'cache_selected_only': 'False', 'send_anonymous_usage_stats': 'True', 'use_colors': 'True', 'empty': 'None', 'invocation_command': 'dbt init', 'introspect': 'True', 'write_json': 'True', 'fail_fast': 'False', 'partial_parse': 'True', 'version_check': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'log_cache_events': 'False', 'log_format': 'default', 'warn_error': 'None', 'debug': 'False', 'printer_width': '80', 'profiles_dir': '/home/dataricardom/.dbt', 'no_print': 'None', 'use_experimental_parser': 'False', 'log_path': 'logs', 'static_parser': 'True'}
[0m23:37:08.975130 [debug] [MainThread]: Starter project path: /home/dataricardom/.cache/pypoetry/virtualenvs/1-local-setup-4NIWAHsR-py3.12/lib/python3.12/site-packages/dbt/include/starter_project
[0m23:37:08.982410 [info ] [MainThread]: 
Your new dbt project "dbt_dw" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m23:37:08.984081 [info ] [MainThread]: Setting up your profile.
[0m23:40:45.395498 [info ] [MainThread]: Profile dbt_dw written to /home/dataricardom/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m23:40:45.399820 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 244.37508, "process_in_blocks": "528", "process_kernel_time": 0.161087, "process_mem_max_rss": "123828", "process_out_blocks": "39088", "process_user_time": 2.436414}
[0m23:40:45.402042 [debug] [MainThread]: Command `dbt init` succeeded at 23:40:45.401723 after 244.38 seconds
[0m23:40:45.403357 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1be23fa0f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1be23ebf80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1be16cab70>]}
[0m23:40:45.404440 [debug] [MainThread]: Flushing usage events
[0m23:40:46.338940 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:45:51.509442 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f19f086c770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f19f138bfe0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f19f138bc50>]}


============================== 14:45:51.513717 | fa2c5af3-68a6-40cd-b7f7-8eadd606d4d6 ==============================
[0m14:45:51.513717 [info ] [MainThread]: Running with dbt=1.10.11
[0m14:45:51.514228 [debug] [MainThread]: running dbt with arguments {'target_path': 'None', 'use_experimental_parser': 'False', 'write_json': 'True', 'invocation_command': 'dbt deps', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'warn_error': 'None', 'send_anonymous_usage_stats': 'True', 'log_format': 'default', 'introspect': 'True', 'fail_fast': 'False', 'log_cache_events': 'False', 'cache_selected_only': 'False', 'no_print': 'None', 'debug': 'False', 'partial_parse': 'True', 'version_check': 'True', 'empty': 'None', 'use_colors': 'True', 'printer_width': '80', 'static_parser': 'True', 'indirect_selection': 'eager', 'log_path': 'logs', 'quiet': 'False', 'profiles_dir': '/home/dataricardom/.dbt'}
[0m14:45:51.514757 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/dataricardom/Workspace/workshop_airflow_dbt_cosmos/2_data_warehouse/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:45:51.515772 [debug] [MainThread]: Resource report: {"command_name": "deps", "command_success": false, "command_wall_clock_time": 0.053478617, "process_in_blocks": "57176", "process_kernel_time": 0.113509, "process_mem_max_rss": "99948", "process_out_blocks": "16", "process_user_time": 1.09915}
[0m14:45:51.516148 [debug] [MainThread]: Command `dbt deps` failed at 14:45:51.516077 after 0.05 seconds
[0m14:45:51.516467 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f19f09971a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f19f08f12e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f19f08f1d00>]}
[0m14:45:51.516778 [debug] [MainThread]: Flushing usage events
[0m14:45:52.233711 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:46:49.611738 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe710f25d00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe7117e1340>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe71198b3b0>]}


============================== 16:46:49.614533 | d8103868-1840-4427-812f-d00e949a3f28 ==============================
[0m16:46:49.614533 [info ] [MainThread]: Running with dbt=1.10.11
[0m16:46:49.615047 [debug] [MainThread]: running dbt with arguments {'use_experimental_parser': 'False', 'partial_parse': 'True', 'fail_fast': 'False', 'log_format': 'default', 'write_json': 'True', 'target_path': 'None', 'empty': 'False', 'printer_width': '80', 'send_anonymous_usage_stats': 'True', 'invocation_command': 'dbt build --exclude resource-type seed', 'log_cache_events': 'False', 'introspect': 'True', 'profiles_dir': '/home/dataricardom/.dbt', 'warn_error': 'None', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'log_path': 'logs', 'indirect_selection': 'eager', 'debug': 'False', 'use_colors': 'True', 'no_print': 'None', 'quiet': 'False', 'cache_selected_only': 'False', 'version_check': 'True'}
[0m16:46:49.615481 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/dataricardom/Workspace/workshop_airflow_dbt_cosmos/2_data_warehouse/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:46:49.616155 [debug] [MainThread]: Resource report: {"command_name": "build", "command_success": false, "command_wall_clock_time": 0.05092141, "process_in_blocks": "32", "process_kernel_time": 0.064561, "process_mem_max_rss": "99776", "process_out_blocks": "8", "process_user_time": 1.081685}
[0m16:46:49.616534 [debug] [MainThread]: Command `dbt build` failed at 16:46:49.616464 after 0.05 seconds
[0m16:46:49.616816 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe710f95df0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe710bec050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe71179cec0>]}
[0m16:46:49.617146 [debug] [MainThread]: Flushing usage events
[0m16:46:50.346776 [debug] [MainThread]: An error was encountered while trying to flush usage events
